### ISSUE TITLE
Error: Cannot find module './src/database'

### ISSUE THREAD

**Issue by KitsuneSolar** [barisusakli/nodebb-plugin-dbsearch#32]
After update NodeBB 1.4.5 to 1.5.1

- NodeBB v1.5.1
- NodeJS v6.10.3

```
4/6 00:16:19 [5314] - error: Error: Cannot find module './src/database'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at Object.<anonymous> (/public_html/node_modules/nodebb-plugin-dbsearch/lib/dbsearch.js:11:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/public_html/node_modules/nodebb-plugin-dbsearch/index.js:1:80)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
4/6 00:16:19 [5314] - warn: [plugins] Unable to parse library for: nodebb-plugin-dbsearch

```

**Comment by barisusakli** [comment]
How are you starting nodebb? Is this happening when you start from nodebb folder with `node app.js`?

**Comment by barisusakli** [comment]
Let me know if above commit fixes the issue.

**Comment by KitsuneSolar** [comment]
> How are you starting nodebb? Is this happening when you start from nodebb folder with node app.js?

```
node ~/public_html/nodebb start
```

**Comment by KitsuneSolar** [comment]
> Let me know if above commit fixes the issue.
Fixed!

**Comment by barisusakli** [comment]
2.0.4 released

**Comment by frndxyz** [comment]
your commits not updated in 3.0.3. its giving same error in nodebb 1.11.1.
